#!/bin/bash
clear
#Install latest security updates
sudo apt update && sudo apt upgrade -y && sudo apt full-upgrade -y && sudo apt autoremove -y && sudo apt clean && sudo apt autoclean

#Install packages required support packages
sudo apt update && sudo apt install -y build-essential pkg-config wget xz-utils libssl-dev zlib1g-dev \
libbz2-dev liblzma-dev libffi-dev libsqlite3-dev libreadline-dev libncurses-dev tk-dev uuid-dev libgdbm-dev \
libgdbm-compat-dev libzstd-dev openssh-server git curl

#Allow SSH logins
# Target configuration file
SSH_CONFIG="/etc/ssh/sshd_config"

# Enable PermitRootLogin
if grep -qE "^\s*#?\s*PermitRootLogin" "$SSH_CONFIG"; then
    sudo sed -i 's/^\s*#\?\s*PermitRootLogin.*/PermitRootLogin yes/' "$SSH_CONFIG"
else
    echo "PermitRootLogin yes" | sudo tee -a "$SSH_CONFIG" > /dev/null
fi

# Enable PasswordAuthentication
if grep -qE "^\s*#?\s*PasswordAuthentication" "$SSH_CONFIG"; then
    sudo sed -i 's/^\s*#\?\s*PasswordAuthentication.*/PasswordAuthentication yes/' "$SSH_CONFIG"
else
    echo "PasswordAuthentication yes" | sudo tee -a "$SSH_CONFIG" > /dev/null
fi

# Restart SSH service
sudo systemctl restart ssh

# Download and install NVIDIA 535.309.01 Drivers
wget -c https://download.nvidia.com/XFree86/Linux-x86_64/535.309.01/NVIDIA-Linux-x86_64-535.309.01.run
chmod +x NVIDIA-Linux-x86_64-535.309.01.run
./NVIDIA-Linux-x86_64-535.309.01.run --no-kernel-modules -s

# Python 3.12.15 on Ubuntu, installed just for you (no sudo) to $HOME/python/3.12.15
# Options: -march=native
# Generated by https://www.build-python-from-source.com/ - run it in bash. Uninstall: rm -rf $HOME/python/3.12.15

# Build dependencies need an administrator; ask them to run:
#   sudo apt-get update
#   sudo DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a apt-get install -y build-essential \
#       pkg-config wget xz-utils libssl-dev zlib1g-dev libbz2-dev liblzma-dev \
#       libffi-dev libsqlite3-dev libreadline-dev libncurses-dev tk-dev uuid-dev \
#       libgdbm-dev libgdbm-compat-dev libzstd-dev
#   sudo DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a apt-get install -y libmpdec-dev  # not packaged everywhere - an error here is fine

# Download and unpack
mkdir -p ~/python-build
cd ~/python-build
wget -c https://www.python.org/ftp/python/3.12.15/Python-3.12.15.tgz
tar xzf Python-3.12.15.tgz
cd Python-3.12.15

# Configure and build (as your user)
./configure --prefix="$HOME/python/3.12.15" \
    --with-ensurepip=install \
    CFLAGS="-march=native"
if make -j "$(nproc)"; then
    # Install
    make altinstall
    cd ~
    rm -rf ~/python-build
else
    echo "WARNING: the build failed, so nothing was installed - see the errors above and config.log in $PWD" >&2
fi

# Set up
ln -sfn python3.12 "$HOME/python/3.12.15/bin/python3"
ln -sfn python3.12 "$HOME/python/3.12.15/bin/python"
ln -sfn pip3.12 "$HOME/python/3.12.15/bin/pip3"
ln -sfn pip3.12 "$HOME/python/3.12.15/bin/pip"
ln -sfn pydoc3.12 "$HOME/python/3.12.15/bin/pydoc"
ln -sfn idle3.12 "$HOME/python/3.12.15/bin/idle"
ln -sfn python3.12-config "$HOME/python/3.12.15/bin/python-config"
echo 'export PATH="$HOME/python/3.12.15/bin:$PATH"' >> ~/.bashrc
export PATH="$HOME/python/3.12.15/bin:$PATH"




















sudo ufw allow ssh && sudo ufw allow 8188/tcp
sudo ufw enable

